CREATE SEQUENCE SQC_CONDITION
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

CREATE SEQUENCE SQC_ETUDIANT
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

CREATE SEQUENCE SQC_FACULTE
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

CREATE SEQUENCE SQC_FILIERE
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

CREATE SEQUENCE SQC_FILIERE_ADMET_MASTER
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

CREATE SEQUENCE SQC_INFO_ACADEMIQUE
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

CREATE SEQUENCE SQC_INSCRIPTION
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

CREATE SEQUENCE SQC_LISTE_ATTENTE
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

CREATE SEQUENCE SQC_MASTER
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

CREATE SEQUENCE SQC_NOTE_CONCOURS
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

CREATE SEQUENCE SQC_PRESELECTION
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

CREATE SEQUENCE SQC_RESPONSABLE
   START WITH 1
   INCREMENT BY 1
   NOCACHE;

CREATE SEQUENCE SQC_UNIVERSITE
   START WITH 1
   INCREMENT BY 1
   NOCACHE;
